SELECT 
	sinfo.SHARENUMBER,
	sinfo.SHAREPRICE,
	sinfo.SHARECOMMISSION,
	ca.TRANSAMOUNT,
	ca.TRANSDATE,
	s.STOCKNAME,
	s.SYMBOL
FROM SHAREINFO_V1 AS sinfo
JOIN CHECKINGACCOUNT_V1 AS ca ON sinfo.CHECKINGACCOUNTID = ca.TRANSID
JOIN TRANSLINK_V1 AS tl ON sinfo.CHECKINGACCOUNTID = tl.CHECKINGACCOUNTID
JOIN STOCK_V1 AS s ON s.STOCKID = tl.LINKRECORDID
WHERE s.STOCKID = 3
ORDER BY ca.TRANSDATE ASC